export enum SCREEN_NAME {
  SPLASH = "SPLASH",
  MAIN = "MAIN",
  MAIN_STACK = "MAIN_STACK",

  HOME = "HOME",
  HOME_STACK = "HOME_STACK",

  CATEGORIES = "CATEGORIES",
  CATEGORIES_STACK = "CATEGORIES_STACK",
  SUB_CATEGORIES_DETAIL = "SUB_CATEGORIES_DETAIL",

  USER = "USER",
  USER_STACK = "USER_STACK",

  SEARCH = "SEARCH",
  SEARCH_STACK = "SEARCH_STACK",

  PRODUCT_STACK = "PRODUCT_STACK",
  PRODUCT = "PRODUCT",
  PRODUCT_DETAIL = "PRODUCT_DETAIL",

  SETTING = "SETTING",
  SETTING_STACK = "SETTING_STACK",
}
